# site settings

title: Cercas Electricas El Maestro
subtitle: "https://elmaestrocr.com"
email: navajasegura@hotmail.com
description: Su mejor opción en seguridad perimetral. </br> Proteja su casa, negocio y a sus seres queridos con ayuda de nosotros.
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

#seo
author: 
  twitter:  "El Maestro"
facebook:
  app_id: "933911333770500"
# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 2

# social settings
facebook_url: https://www.facebook.com/cercaselectricaselmaestro/
instagram_url: https://www.instagram.com/cercaselectricaselmaestro/

twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown
# permalink: /:title/
sass:
  style: compressed

plugins:
  # - jekyll-sitemap
  - jekyll-seo-tag
